name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # O 'master' si tu rama principal se llama así

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

env:
  ASTRO_TELEMETRY_DISABLED: 1

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tu código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-level: 20
          cache: 'npm' # Cambia a pnpm o yarn si usas otro

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar sitio con Astro
        run: npm run build

      - name: Subir artefacto para Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # La carpeta que genera Astro

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4